import { DM_Sans, Geist_Mono } from "next/font/google";
import "./globals.css";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});
const geist = Geist_Mono({
  variable: "--font-geist",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pimjo test",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${geist.variable} font-dm antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
